#Gramáticas usadas para o MiniC++ (uma versão simplificada do C++)

# Elementos léxicos

# Dígitos decimais básicos 
digito ::= "0"| "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;
digito_nao_nulo ::= "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;

# Números
numero_inteiro ::= "0" | digito_nao_nulo (digito)* ;

numero_real ::= digito_nao_nulo digito* "." digito+ | "0" "." digito+ ;

numero ::= numero_inteiro | numero_real;

# Letras maiúsculas e minúsculas para nomes 
letra ::= "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" 
        | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t" 
        | "u" | "v" | "w" | "x" | "y" | "z"
        | "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" 
        | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" | "S" | "T" 
        | "U" | "V" | "W" | "X" | "Y" | "Z" ;

# Caracteres
caractere ::= letra | digito | " ";

# Identificador: nomes de variáveis e funções ( obrigatoriamente deve começar com letra)
identificador ::= (letra) (letra | digito | "_")* ;

# Tipos de dados aceitos no MiniC++
tipo_basico ::= "int" | "char" | "double" | "bool" | "string" ;

tipo_retorno ::= tipo_basico | "void";

# literais
literal_bool ::= "true" | "false" ;

literal_char ::= "'" caractere "'";

literal_string ::= '"' caractere* '"' ;

literal ::= numero | literal_bool | literal_char | literal_string ;

# Operadores aritméticos e lógicos
op_aditivo ::= "+" | "-" ;

op_multiplicativo ::= "*" | "/" | "%" ;

op_relacional ::= "<" | "<=" | ">" | ">=" ;

op_igualdade ::= "==" | "!=" ;

op_logico_and ::= "&&" ;

op_logico_or ::= "||" ;

op_atribuicao ::= "=" | "+=" | "-=" ;

op_unario ::= "!" ;

# Regras para expressões matemáticas e lógicas, considerandoa hierarquia de prioridade entre as expressões
fator ::= literal
        | identificador
        | acesso_array
        | chamada_funcao
        | incremento
        | "(" expressao ")"
        | op_unario fator ;

# Regra sobre multiplicação, divisão
termo ::= fator (op_multiplicativo fator)* ;

# Regra que cuida da soma e subtração
expr_aritmetica ::= termo (op_aditivo termo)* ;

expressao_relacional ::= expr_aritmetica (op_relacional expr_aritmetica)* ;

expressao_igualdade ::= expressao_relacional (op_igualdade expressao_relacional)* ;

expressao_and ::= expressao_igualdade (op_logico_and expressao_igualdade)* ;

expressao_or ::= expressao_and (op_logico_or expressao_and)* ;

expressao_ternaria ::= expressao_or ("?" expressao ":" expressao)? ;

expressao ::= expressao_ternaria ;

# Array 
acesso_array ::= identificador "[" expressao "]" ;

# Apenas pós-fixado: i++ e i--
incremento ::= identificador "++"
             | identificador "--"
             | acesso_array "++"
             | acesso_array "--" ;

# Declaração de variáveis
declarador ::= identificador ("=" expressao)? ;

declaracao_variavel ::= tipo_basico declarador ("," declarador)* ";" ;

# Declaração de Arrays - permitidos somente para o tipo int
declaracao_array ::= "int" identificador "[" numero_inteiro "]" ";" ;

# Atribuição 
destino ::= identificador | acesso_array ;

atribuicao ::= destino op_atribuicao expressao ";" ;

atribuicao_sem_terminador ::= destino op_atribuicao expressao ;

# Funções 

# Chamada de funções
chamada_funcao ::= identificador "(" argumentos? ")" ;

argumentos ::= expressao ("," expressao)* ;

# Declaração de funções
parametro ::= tipo_basico identificador ;

parametros ::= parametro ("," parametro)* ;

declaracao_funcao ::= tipo_retorno identificador "(" parametros? ")" bloco ;

# Condicionais
comando_if ::= "if" "(" expressao ")" comando
               ("else" comando)? ;

# While
comando_while ::= "while" "(" expressao ")" comando ;

# For
declaracao_variavel_sem_terminador ::= tipo_basico declarador ("," declarador)* ;

inicializacao_for ::= declaracao_variavel_sem_terminador | atribuicao_sem_terminador;

incremento_for ::= incremento | atribuicao_sem_terminador ;

comando_for ::= "for" "(" inicializacao_for ";" expressao ";" incremento_for ")" comando ;

# Break e continue
comando_break ::= "break" ";" ;

comando_continue ::= "continue" ";" ;

# Return
comando_return ::= "return" expressao? ";" ;

# Entrada e saída

#Entrada
destino_entrada ::= identificador | acesso_array ;

comando_cin ::= "cin" ">>" destino_entrada (">>" destino_entrada)* ";" ;

# Saída
comando_cout ::= "cout" "<<" expressao ("<<" expressao)* ";" ;

# Blocos
bloco ::= "{" comando* "}" ;

# Comandos (statements) possíveis
comando ::= declaracao_variavel
          | declaracao_array
          | atribuicao
          | comando_if
          | comando_while
          | comando_for
          | comando_break
          | comando_continue
          | comando_return
          | comando_cin
          | comando_cout
          | bloco
          | expressao ";" ;

# Função main
funcao_main ::= "int" "main"  "("  ")"  bloco ;

# Programa
programa ::= declaracao_funcao*
             funcao_main ;